/*
 * This file is part of the Meeds project (https://meeds.io/).
 * Copyright (C) 2020 Meeds Association
 * contact@meeds.io
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package org.exoplatform.services.rpc;

import java.io.Serializable;

/**
 *  This class represents the command that can be executed on a remote server.
 *  A RemoteCommand needs to be ThreadSafe since it can be re-used by several
 *  threads in parallel.
 * @author <a href="mailto:nicolas.filotto@exoplatform.com">Nicolas Filotto</a>
 * @version $Id$
 */
public interface RemoteCommand
{
   /**
    * This method will execute the command on the local machine.
    * @param args The parameters needed to execute the command
    * @return arbitrary return value generated by performing this command
    * @throws Throwable in the event of problems.
    */
   Serializable execute(Serializable[] args) throws Throwable;

   /**
    * Gives the id of the command
    * @return the unique ID of the command
    */
   String getId();
}
